export {
  registerController,
  registerControllers,
  // Elysia-style route builders
  get,
  post,
  put,
  patch,
  del,
  noContent,
  type RegisterControllerOptions,
  type KoaHandlerContext,
  type KoaRouteHandler,
  type KoaRouteConfig,
  type KoaRouteDefinition,
  type GetRouteOptions,
  type BodyRouteOptions,
  type ReplyHelpers,
  type ErrorHelpers,
} from './endpoint-registrar.js'
