export {
  registerController,
  registerControllers,
  // Elysia-style route builders
  get,
  post,
  put,
  patch,
  del,
  noContent,
  type RegisterControllerOptions,
  type FastifyHandlerContext,
  type FastifyRouteHandler,
  type FastifyRouteConfig,
  type FastifyRouteDefinition,
  type GetRouteOptions,
  type BodyRouteOptions,
  type ReplyHelpers,
  type ErrorHelpers,
} from './endpoint-registrar.js'
